version: "3"
services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.prpd
      args:
        - REACT_APP_NAME=yuriko_prod
    ports:
      - "8080:80"
    volumes:
      - ./src:/app/src
    # env_file:
    #   - ./.env